language: objective-c
osx_image: xcode8.2
cache:
  - bundler
  - cocoapods
before_install:
  - ./install_swiftlint.sh
  - bundle install
  - bundle exec pod install --repo-update
before_script:
  - make lint
script:
  - make test
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f fastlane/test_output/cobertura.xml
